ALTER TABLE render_events ADD COLUMN IF NOT EXISTS phase SMALLINT NOT NULL DEFAULT 2;
ALTER TABLE render_events ADD COLUMN IF NOT EXISTS component_path TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE render_events ADD COLUMN IF NOT EXISTS commit_time DOUBLE PRECISION NOT NULL DEFAULT 0;
